//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAFE()
        {
            this.CATACION = new HashSet<CATACION>();
        }
    
        public string CODCAFE { get; set; }
        public string TIPOCAFE { get; set; }
        public string CODEVENTO { get; set; }
        public string PROCEDENCIA { get; set; }
        public string ORIGEN { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> PUNTOTUESTE { get; set; }
        public Nullable<int> GRADOMOLIENDA { get; set; }
    
        public virtual ATRIBUTOSCAFE ATRIBUTOSCAFE { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATACION> CATACION { get; set; }
    }
}
