//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATACION()
        {
            this.CATA = new HashSet<CATA>();
        }
    
        public string CODCATACION { get; set; }
        public string CODPANEL { get; set; }
        public string CODCATADOR { get; set; }
        public string CODCAFE { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual CAFE CAFE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATA> CATA { get; set; }
        public virtual CATADOR CATADOR { get; set; }
        public virtual PANEL PANEL { get; set; }
    }
}
