//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATA
    {
        public string CODCATACION { get; set; }
        public int VEZCATADA { get; set; }
        public Nullable<int> RANCIDEZ { get; set; }
        public Nullable<int> DULCE { get; set; }
        public Nullable<int> ACIDEZ { get; set; }
        public Nullable<int> AROMA { get; set; }
        public Nullable<int> AMARGO { get; set; }
        public Nullable<int> FRAGANCIA { get; set; }
        public Nullable<int> SABORESIDUAL { get; set; }
        public Nullable<int> CUERPO { get; set; }
        public Nullable<int> IMPRESIONGLOBAL { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CATACION CATACION { get; set; }

    }
}
