//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatafexEntities : DbContext
    {
        public CatafexEntities()
            : base("name=CatafexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<ATRIBUTOSCAFE> ATRIBUTOSCAFE { get; set; }
        public virtual DbSet<CAFE> CAFE { get; set; }
        public virtual DbSet<CATA> CATA { get; set; }
        public virtual DbSet<CATACION> CATACION { get; set; }
        public virtual DbSet<CATADOR> CATADOR { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<PANEL> PANEL { get; set; }
        public virtual DbSet<REPORTE> REPORTE { get; set; }
    }
}
