//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public string CODREPORTE { get; set; }
        public string RUTAGRAFICO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CODPANEL { get; set; }
    
        public virtual PANEL PANEL { get; set; }
    }
}
